In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3  = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [4]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
states

['California', 'Ohio', 'Oregon', 'Texas']

In [5]:
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [6]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [7]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [8]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [9]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [10]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [11]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [12]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [13]:
obj3 == obj4

ValueError: Can only compare identically-labeled Series objects

In [14]:
obj3.isnull() == obj4.isnull()

ValueError: Can only compare identically-labeled Series objects

In [15]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [16]:
obj

NameError: name 'obj' is not defined

In [17]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [18]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [19]:
data = {'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year'  : [2000, 2001, 2002, 2001, 2002, 2003],
        'pop'   : [1.5, 1, 2, 3.0, 5, 6]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.0
2    Ohio  2002  2.0
3  Nevada  2001  3.0
4  Nevada  2002  5.0
5  Nevada  2003  6.0

In [21]:
datat = {'state': ['CA', 'NY'],
         'code' : [1, 2]}
framet = pd.DataFrame(datat)
framet

state  code
0    CA     1
1    NY     2

In [22]:
datat  = [1, 2, 3]
framet = pd.DataFrame(datat)
framet

0
0  1
1  2
2  3

In [25]:
indeks = ['hello']
framet.index.name = indeks
framet

0
[hello]   
0        1
1        2
2        3

In [26]:
frame.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.0

In [27]:
frame.tail(3)

state  year  pop
3  Nevada  2001  3.0
4  Nevada  2002  5.0
5  Nevada  2003  6.0

In [28]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.0
2  2002    Ohio  2.0
3  2001  Nevada  3.0
4  2002  Nevada  5.0
5  2003  Nevada  6.0

In [29]:
cols   = ['year', 'state', 'pop', 'debt']
index  = ['one', 'two', 'three', 'four', 'five', 'six']
frame2 = pd.DataFrame(data, columns=cols, index=index)
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.0  NaN
three  2002    Ohio  2.0  NaN
four   2001  Nevada  3.0  NaN
five   2002  Nevada  5.0  NaN
six    2003  Nevada  6.0  NaN

In [33]:
x, *rest = frame2.columns
x

'year'

In [34]:
frame[x]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [35]:
np.unique(frame[x])

array([2000, 2001, 2002, 2003])

In [36]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.0  NaN
three  2002    Ohio  2.0  NaN
four   2001  Nevada  3.0  NaN
five   2002  Nevada  5.0  NaN
six    2003  Nevada  6.0  NaN

In [39]:
frame2.loc['three']

year     2002
state    Ohio
pop         2
debt      NaN
Name: three, dtype: object

In [40]:
frame2.debt = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.0  16.5
three  2002    Ohio  2.0  16.5
four   2001  Nevada  3.0  16.5
five   2002  Nevada  5.0  16.5
six    2003  Nevada  6.0  16.5

In [42]:
frame2.loc['two']['state']

'Ohio'

In [43]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.0   1.0
three  2002    Ohio  2.0   2.0
four   2001  Nevada  3.0   3.0
five   2002  Nevada  5.0   4.0
six    2003  Nevada  6.0   5.0

In [44]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [45]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.0  -1.2
three  2002    Ohio  2.0   NaN
four   2001  Nevada  3.0  -1.5
five   2002  Nevada  5.0  -1.7
six    2003  Nevada  6.0   NaN

In [46]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.0  -1.2     True
three  2002    Ohio  2.0   NaN     True
four   2001  Nevada  3.0  -1.5    False
five   2002  Nevada  5.0  -1.7    False
six    2003  Nevada  6.0   NaN    False

In [47]:
del frame2['eastern']

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.0  -1.2
three  2002    Ohio  2.0   NaN
four   2001  Nevada  3.0  -1.5
five   2002  Nevada  5.0  -1.7
six    2003  Nevada  6.0   NaN

In [51]:
pop = {'Nevada': {2001: 2.4,
                  2002: 2.9},
       'Ohio'  : {2000: 1.5,
                  2001: 1.7,
                  2002: 3.6}}
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [52]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [53]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [54]:
index = [2001, 2002, 2003]
pd.DataFrame(pop, index=index)

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [55]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [56]:
frame3.index.name   = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [57]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [58]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.0, -1.2],
       [2002, 'Ohio', 2.0, nan],
       [2001, 'Nevada', 3.0, -1.5],
       [2002, 'Nevada', 5.0, -1.7],
       [2003, 'Nevada', 6.0, nan]], dtype=object)

##Index objects 

In [59]:
index = ['a', 'b', 'c']
obj = pd.Series(range(3), index=index)
obj

a    0
b    1
c    2
dtype: int64

In [60]:
indeks = obj.index
indeks

Index(['a', 'b', 'c'], dtype='object')

In [61]:
indeks[1:]

Index(['b', 'c'], dtype='object')

In [62]:
indeks[1] = 'd'

TypeError: Index does not support mutable operations

In [63]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [64]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [65]:
obj2.index is labels

True

In [66]:
obj2.index == labels

array([ True,  True,  True])

In [67]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [68]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [69]:
'Ohio' in frame3.columns

True

In [70]:
2010 in frame3.index

False

In [72]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [ ]:
# Essential Functionality

In [73]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [75]:
new_index = ['a',  'b', 'c', 'd', 'e']
obj2 = obj.reindex(new_index)
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [76]:
dat3 = ['blue', 'purple', 'yellow']
ind3 = [0, 2, 4]
obj3 = pd.Series(dat3, index=ind3)
obj3

0      blue
2    purple
4    yellow
dtype: object

In [77]:
rind3 = range(6)
obj3.reindex(rind3, method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [78]:
dat4  = np.arange(9).reshape((3, 3))
ind4  = ['a', 'c', 'd']
col4  = ['Ohio', 'Texas', 'California']
frame = pd.DataFrame(dat4, index=ind4, columns=col4)
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [79]:
rind4  = ['a', 'b', 'c', 'd']
frame2 = frame.reindex(rind4)
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [80]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [81]:
frame.loc[['a', 'b', 'c', 'd'], states]

/Users/mkamaal/Workarea/MachineLearning/HandsOnMLSCTF/chapter2/env/lib/python3.7/site-packages/pandas/core/indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [83]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [84]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [85]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [86]:
index = ['Ohio', 'Colorado', 'Utah', "New York"]
col   = ['one', 'two', 'three', 'four']
dta   = np.arange(16).reshape((4, 4))
data  = pd.DataFrame(dta, index=index, columns=col)
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [87]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [88]:
data.drop(['two'], axis='columns')

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [89]:
data.drop('two', axis=2)

ValueError: No axis named 2 for object type <class 'type'>

In [ ]:
## Indexing, selection, filtering

In [91]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [92]:
obj['b']

1.0

In [93]:
obj[1]

1.0

In [94]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [95]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [96]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [97]:
obj[obj > 2]

d    3.0
dtype: float64

In [98]:
condition = obj > 2
obj[condition]

d    3.0
dtype: float64

In [99]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [100]:
obj['b':'c'] = 5

In [101]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [102]:
dat   = np.arange(16).reshape((4, 4))
index = ['Ohio', 'Colorado', 'Utah', 'New York']
cols  = ['one', 'two', 'three', 'four']

data  = pd.DataFrame(dat, index=index, columns=cols)
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [103]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [104]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [105]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [106]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [107]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [108]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [109]:
pd

<module 'pandas' from '/Users/mkamaal/Workarea/MachineLearning/HandsOnMLSCTF/chapter2/env/lib/python3.7/site-packages/pandas/__init__.py'>

In [110]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [111]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [112]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [113]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [114]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [115]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [116]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [117]:
ser[-1]

KeyError: -1

In [118]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [119]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [120]:
ser2[-1]

2.0

In [121]:
ser[:1]

0    0.0
dtype: float64

In [122]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [123]:
ser.iloc[:1]

0    0.0
dtype: float64

In [125]:
dat = [7.3, -2.5, 3.4, 1.5]
ind = ['a', 'c', 'd', 'e']
s1  = pd.Series(dat, index=ind)

dat1 = [-2.1, 3.6, -1.5, 4, 3.1]
ind2 = ['a', 'c', 'e', 'f', 'g']
s2   = pd.Series(dat1, index=ind2)

s1;s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [126]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [129]:
dat1 = np.arange(9.).reshape((3, 3))
dat2 = np.arange(12.).reshape((4, 3))

col1 = list('bcd')
col2 = list('bde')

ind1 = ["Ohio", "Texas", "Colorado"]
ind2 = ["Utah", "Ohio", "Texas", "Oregon"]

df1  = pd.DataFrame(dat1, columns=col1, index=ind1)
df2  = pd.DataFrame(dat2, columns=col2, index=ind2)

df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [130]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [131]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [132]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

A
0  1
1  2

In [133]:
df2

B
0  3
1  4

In [134]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [135]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [136]:
dat1 = np.arange(12.).reshape(3, 4)
dat2 = np.arange(20.).reshape(4, 5)

col1 = list('abcd')
col2 = list('abcde')

df1  = pd.DataFrame(dat1, columns=col1)
df2  = pd.DataFrame(dat2, columns=col2)

df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [137]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [141]:
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e  (1, b)
0   0.0   1.0   2.0   3.0   4.0     NaN
1   5.0   NaN   7.0   8.0   9.0     NaN
2  10.0  11.0  12.0  13.0  14.0     NaN
3  15.0  16.0  17.0  18.0  19.0     NaN

In [142]:
df1 + df2

(1, b)     a     b     c     d   e
0     NaN   0.0   2.0   4.0   6.0 NaN
1     NaN   9.0   NaN  13.0  15.0 NaN
2     NaN  18.0  20.0  22.0  24.0 NaN
3     NaN   NaN   NaN   NaN   NaN NaN

In [144]:
df1.add(df2, fill_value=0)

(1, b)     a     b     c     d     e
0     NaN   0.0   2.0   4.0   6.0   4.0
1     NaN   9.0   5.0  13.0  15.0   9.0
2     NaN  18.0  20.0  22.0  24.0  14.0
3     NaN  15.0  16.0  17.0  18.0  19.0

In [145]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [146]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [147]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e  (1, b)
0  0.0  1.0   2.0   3.0  0       0
1  4.0  5.0   6.0   7.0  0       0
2  8.0  9.0  10.0  11.0  0       0

In [148]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [149]:
arr[0]

array([0., 1., 2., 3.])

In [150]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [151]:
dat = np.arange(12.).reshape((4, 3))
col = list('bde')
ind = ['Utah', 'Ohio', 'Texas', 'Oregon']

frame = pd.DataFrame(dat, columns=col, index=ind)
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [152]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [153]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [155]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [156]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [157]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [158]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [159]:
#######

dat = np.random.randn(4, 3)
col = list('bde')
ind = ['Utah', 'Ohio', 'Texas', 'Oregon']

frame = pd.DataFrame(dat, columns=col, index=ind)
frame

b         d         e
Utah    0.146006  0.333326  0.380384
Ohio    1.553876 -0.315749  1.373486
Texas   1.679261 -0.363221  0.385298
Oregon  0.030277  0.283831 -0.493889

In [160]:
np.abs(frame)

b         d         e
Utah    0.146006  0.333326  0.380384
Ohio    1.553876  0.315749  1.373486
Texas   1.679261  0.363221  0.385298
Oregon  0.030277  0.283831  0.493889

In [161]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.648983
d    0.696547
e    1.867375
dtype: float64

In [162]:
frame.apply(f, axis='columns')

Utah      0.234378
Ohio      1.869625
Texas     2.042482
Oregon    0.777720
dtype: float64

In [163]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min  0.030277 -0.363221 -0.493889
max  1.679261  0.333326  1.373486

In [164]:
format = lambda x: '%.2f' % x

frame.applymap(format)

b      d      e
Utah    0.15   0.33   0.38
Ohio    1.55  -0.32   1.37
Texas   1.68  -0.36   0.39
Oregon  0.03   0.28  -0.49

In [165]:
frame['e'].map(format)

Utah       0.38
Ohio       1.37
Texas      0.39
Oregon    -0.49
Name: e, dtype: object

In [166]:
dat = range(4)
ind = ['d', 'a', 'b', 'c']
obj = pd.Series(dat, index=ind)
obj

d    0
a    1
b    2
c    3
dtype: int64

In [167]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [169]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [170]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [171]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [172]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [174]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [175]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [176]:
frame = pd.DataFrame({'b': [4, 7, -3, 2],
                      'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [177]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [178]:
frame.sort_values(by='b', ascending=False)

b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [179]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [180]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [181]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [2]:
import pandas_datareader.data as web

In [3]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0   
 2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0   
 2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0   
 2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0   
 2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0   
 2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0   
 2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0   
 2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0   
 2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0   
 2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0   
 2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0   
 201

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
price = pd.DataFrame({ticker: data['Adj Close']
                      for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                       for ticker, data in all_data.items()})


In [6]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-03-18  0.010209  0.005594  0.014321 -0.000169
2019-03-19 -0.007925  0.001997  0.000680  0.012320
2019-03-20  0.008739 -0.006335 -0.001105  0.020953
2019-03-21  0.036830  0.013180  0.022975  0.006185
2019-03-22  0.009585  0.000000 -0.007145 -0.003313

In [7]:
returns['MSFT'].corr(returns['IBM'])

0.4878053924781747

In [8]:
returns['MSFT'].cov(returns['IBM'])

8.723316717459547e-05

In [9]:
obj = pd.Series('c a d a a b b c c'.split())
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [10]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [11]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [12]:
pd.value_counts(obj.values, sort=False)

b    2
c    3
d    1
a    3
dtype: int64

In [13]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [14]:
mask = obj.isin('b c'.split())
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [ ]:
obj[mask]